name = "ImageMagick_jll"
uuid = "c73af94c-d91f-53ed-93a7-00f77d67a9d7"
version = "6.9.10-12+0"

[deps]
JpegTurbo_jll = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
libpng_jll = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
Libtiff_jll = "89763e89-9b03-5906-acba-b20f662cd828"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.3"
